services:
  - type: web
    name: good-girl-points-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://good-girl-points-frontend.onrender.com

  - type: web
    name: good-girl-points-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://good-girl-points-backend.onrender.com 